camera: 0
face: false
face_method: eigen
hands: 2
main_hand: Right
mouse_sensitivity: 3.5
navigation:
  double_left_click:
  - '11000'
  - '01000'
  drag_and_drop:
  - '01111'
  - '01000'
  faster_move:
  - '00000'
  - '11000'
  left_click:
  - '01000'
  - '01000'
  move:
  - '00000'
  - '01000'
  right_click:
  - '00001'
  - '01000'
  scroll:
  - '01110'
  - '01000'
