import cv2

TEXT_POSITION = (10, 50)
TEXT_FONT = cv2.FONT_HERSHEY_PLAIN
TEXT_FONT_SCALE = 1.5
TEXT_COLOR = (255, 0, 0)
TEXT_FONT_THICKNESS = 2

def put_text(img, text):
    cv2.putText(img, text, TEXT_POSITION, TEXT_FONT, TEXT_FONT_SCALE, TEXT_COLOR, TEXT_FONT_THICKNESS)